### PR TITLE
Optionally emit kafka key

### PR DESCRIPTION
**Pull request by d-t-w**
I want to access the key (not just the payload) that is sent by the Producer in the KeyedMessage.

Pull request modifies KafkaConfig to allow for an optional keyScheme, if set the spouts will include key field(s) and the emitter will emit the deserialized key along with the payload.

Default behaviour is unchanged.

### CODE REVIEW

**Comment by wurstmeister** [comment]
Hi, 

thanks for suggestions. I've slightly modified your approach so that it easily works with the KafkaSpout as well (see https://github.com/wurstmeister/storm-kafka-0.8-plus/commit/4de85c8e7f6f4244be9eb688c6a4576a9c88c2a1)

I've added an example for a scheme that supports string keys and values (https://github.com/wurstmeister/storm-kafka-0.8-plus/blob/4de85c8e7f6f4244be9eb688c6a4576a9c88c2a1/src/jvm/storm/kafka/StringKeyValueScheme.java)

Please let me know if this allows you to do what you want.

Thanks

**Comment by d-t-w** [comment]
Hello,

 Yes I think your approach should work fine in my case, I'll need to create a KeyValueScheme which has a String key and Raw payload which is no problem.

**Comment by leerobert** [comment]
I like your approach wurstmeister of generating a key value scheme. I was going to take a stab at implementing 0.8 kafka spout in storm since the starter only incorporates 0.7. Thanks for beating me to the punch and making it open source!

**Comment by wurstmeister** [comment]
Thanks for the feedback!

**Comment by d-t-w** [comment]
Hey @wurstmeister when do you plan on pushing a 0.3.1 (or 0.4) to Clojars? This change would be very handy for my project.

**Comment by wurstmeister** [comment]
Done

**Comment by d-t-w** [comment]
thanks @wurstmeister very much appreciate the time and effort!

**Pull request closed without merging**
