### PR TITLE
modify partitioning across tasks in ZkCoordinator

### PR DESCRIPTION
**Pull request by andrewneilson**
We ran into the same issue as is described in #4 when using KafkaSpout. When attempting to consume from multiple partitions (via multiple spouts), there was no consistency with how the partitions would be assigned to each spout task. Specifically, with an 8 partition topic being consumed from 2 to 8 spouts we would end up with only 1-3 out of the spouts being used.

My small change simplifies the partitioning scheme for KafkaSpout and this has worked for us to distribute consumption from all partitions. I feel like I'm missing something about how `myOwnership` was implemented before though so if that's the case then please enlighten me :).

### CODE REVIEW

**Comment by andrewneilson** [comment]
travis failure seems to be due to a missing `.travis.yml` file? I see that in the other PR too

```
WARNING: We were unable to find a .travis.yml file. This may not be what you
  want. Build will be run with default settings.
Using worker: worker-linux-2-1.bb.travis-ci.org:travis-linux-12
Could not find .travis.yml, using standard configuration.
```

**Comment by wurstmeister** [comment]
Hi, 

thanks for highlighting this issue. I've taken a slightly different approach to fixing it (see https://github.com/wurstmeister/storm-kafka-0.8-plus/commit/2f45866c8e011ac4804c940ff9e1d7c147591761) so that we have some consistency across coordinators and can test things better. I've also added some more logging so it's easier to see what's going on.

Please let me know if this works for you. 

Thanks

**Comment by andrewneilson** [comment]
thanks @wurstmeister I like that approach and will test it today.

**Comment by andrewneilson** [comment]
I tested 2f45866c8e011ac4804c940ff9e1d7c147591761 and didn't quite see it behaving the way I would expect. I left a comment about it on that commit.

**Comment by ryanpersaud** [comment]
This has worked for me in limited testing.  I'll post if I see any unexpcted behavior.  @wurstmeister, do you know if there are any plans to fold this project back into the storm project?  Thanks for the information.

**Comment by phoenixhadoop** [comment]
Hi,everybody
   Have you tested it ok? I will test it today.

**Comment by wurstmeister** [comment]
@ryanpersaud, yes https://github.com/apache/incubator-storm/pull/65

**Comment by andrewneilson** [comment]
Closed this after verifying 2f45866c8e011ac4804c940ff9e1d7c147591761

**Pull request closed without merging**
